### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by jiashizuo** [qbmizsj/A-GCL#3]
I would like to ask how this diagram is drawn, what is on the left half and how to understand it.
![Snipaste_2024-10-23_11-57-13](https://github.com/user-attachments/assets/08a26327-0c99-43d4-a9b9-3d80e4a9a9a4)

**Comment by qbmizsj** [comment]
It was drawn by Matlab. it looks like the common visualization in R. (Raindrop plot). It visualizes the scattered points for each fold and estimated distribution in general ( while just for better visualization)



发自我的iPhone


------------------ Original ------------------
From: zzz ***@***.***&gt;
Date: Wed,Oct 23,2024 11:59 AM
To: qbmizsj/A-GCL ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [qbmizsj/A-GCL] About Visualization (Issue #3)





 
I would like to ask how this diagram is drawn, what is on the left half and how to understand it.
 Snipaste_2024-10-23_11-57-13.png (view on web)

**Comment by jiashizuo** [comment]
> It was drawn by Matlab. it looks like the common visualization in R. (Raindrop plot). It visualizes the scattered points for each fold and estimated distribution in general ( while just for better visualization) 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: zzz ***@***.***&gt; Date: Wed,Oct 23,2024 11:59 AM To: qbmizsj/A-GCL ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [qbmizsj/A-GCL] About Visualization (Issue #3) I would like to ask how this diagram is drawn, what is on the left half and how to understand it. Snipaste_2024-10-23_11-57-13.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Thank you for your reply
